funny_trip_annonce:
    resource: "@FunnyTripBundle/Controller/AnnonceController.php"
    type:     annotation
    prefix:   /{_locale}/

funny_trip:
    resource: "@FunnyTripBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: fr|en|es

funny_trip_trajet:
    defaults: { _controller: FunnyTripBundle:Default:trajet }
    pattern:   /{_locale}/mes_trajets
    requirements:
            _locale: fr|en|es

funny_trip_reservation:
    defaults: { _controller: FunnyTripBundle:Default:reservation }
    pattern:   /{_locale}/mes_reservations
    requirements:
            _locale: fr|en|es

funnytrip_new_reservation:
    defaults: { _controller: FunnyTripBundle:Default:new_reservation }
    pattern:   /{_locale}/new_reservations
    requirements:
            _locale: fr|en|es

funnytrip_delete_reservation:
    defaults: { _controller: FunnyTripBundle:Default:delete_reservation }
    pattern:   /{_locale}/delete_reservations
    requirements:
            _locale: fr|en|es

funnytrip_feed:
    defaults: { _controller: FunnyTripBundle:Default:feed }
    pattern:   /{_locale}/feed
    requirements:
            _locale: fr|en|es

funnytrip_change_theme:
    defaults: { _controller: FunnyTripBundle:Default:change_theme }
    pattern:   /{_locale}/change_theme
    requirements:
            _locale: fr|en|es

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile
    requirements:
            _locale: fr|en|es

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register
    requirements:
            _locale: fr|en|es

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    requirements:
            _locale: fr|en|es

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/change-password
    requirements:
            _locale: fr|en|es