funny_trip_annonce:
    resource: "@FunnyTripBundle/Controller/AnnonceController.php"
    type:     annotation

funny_trip:
    resource: "@FunnyTripBundle/Resources/config/routing.yml"
    prefix:   /

funny_trip_trajet:
    defaults: { _controller: FunnyTripBundle:Default:trajet }
    pattern:   /mes_trajets

funny_trip_reservation:
    defaults: { _controller: FunnyTripBundle:Default:reservation }
    pattern:   /mes_reservations

funnytrip_new_reservation:
    defaults: { _controller: FunnyTripBundle:Default:new_reservation }
    pattern:   /new_reservations

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password