<?php
/**
 * Created by PhpStorm.
 * User: martin
 * Date: 17/03/2017
 * Time: 11:14
 */

namespace FunnyTrip\Bundle\Repository;

use Doctrine\ORM\EntityRepository;


/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends EntityRepository
{
}
